server:
  port: 10003
spring:
  application:
    name: rpc-client
  http:
    multipart:
      enabled: true
      max-file-size: 102400kb
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:11100/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: true
security:
  basic:
    path:
    - /shutdown
  user:
    name: admin
    password: sftadmin
management:
  security:
    roles:
    - ACTUATOR
service-0:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ServerListRefreshInterval: 5000