server:
  port: 9003
spring:
  config:
    name: server
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes:
          - 192.168.112.134:2181
          zk-connection-timeout: 300
          brokers:
          - 192.168.112.134
    config:
      server:
        git:
          uri: http://192.168.112.134/test/cloudConfig