server:
  port: 9003
spring:
  application:
    name: configserver
  
  rabbitmq:
    host: 192.168.112.134
    port: 5672
    username: asdf
    password: asdf
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benxincaomu/config.git
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:11100/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: true
security:
  basic:
    path:
    - /shutdown
  user:
    name: admin
    password: sftadmin