server:
  port: 10003
spring:
  application:
    name: rpc-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:11100/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: true
security:
  basic:
    path:
    - /shutdown
  user:
    name: admin
    password: sftadmin
management:
  security:
    roles:
    - ACTUATOR